export const countries = [
  { code: 'ZM', label: 'Zambia', phone: '260', phoneLength: 9 },
  { code: 'AO', label: 'Angola', phone: '244', phoneLength: 9 },
  { code: 'BW', label: 'Botswana', phone: '267', phoneLength: 8 },
  { code: 'CD', label: 'DR Congo', phone: '243', phoneLength: 9 },
  { code: 'LS', label: 'Lesotho', phone: '266', phoneLength: 8 },
  { code: 'MW', label: 'Malawi', phone: '265', phoneLength: 9 },
  { code: 'MZ', label: 'Mozambique', phone: '258', phoneLength: 9 },
  { code: 'NA', label: 'Namibia', phone: '264', phoneLength: 9 },
  { code: 'ZA', label: 'South Africa', phone: '27', phoneLength: 9 },
  { code: 'SZ', label: 'Eswatini', phone: '268', phoneLength: 8 },
  { code: 'TZ', label: 'Tanzania', phone: '255', phoneLength: 9 },
  { code: 'ZW', label: 'Zimbabwe', phone: '263', phoneLength: 9 },
  { code: 'CM', label: 'Cameroon', phone: '237', phoneLength: 9 },
  { code: 'CF', label: 'Central African Republic', phone: '236', phoneLength: 8 },
  { code: 'TD', label: 'Chad', phone: '235', phoneLength: 8 },
  { code: 'CG', label: 'Congo, Republic', phone: '242', phoneLength: 9 },
  { code: 'GQ', label: 'Equatorial Guinea', phone: '240', phoneLength: 9 },
  { code: 'GA', label: 'Gabon', phone: '241', phoneLength: 8 },
  { code: 'ST', label: 'Sao Tome & Principe', phone: '239', phoneLength: 7 },
  { code: 'KE', label: 'Kenya', phone: '254', phoneLength: 9 },
  { code: 'UG', label: 'Uganda', phone: '256', phoneLength: 9 },
  { code: 'RW', label: 'Rwanda', phone: '250', phoneLength: 9 },
  { code: 'BI', label: 'Burundi', phone: '257', phoneLength: 8 },
] as const;
